#+title: recur 1
#+ROAM_TAGS: orgmode repeat emacs emacs-elements diary
#+created: [2021-02-22 Mon]
#+last_modified: [2021-02-22 Mon 03:45]
#+STARTUP: showall

diary-file
org-agenda-include-diary

Monday Clean the house
* 22 Pay my municipal bill

* DIARY FLOAT EXPLAINED

Better than this

* Go to visit John
SCHEDULED: <2021-02-22 Mon +1w>

1) Month

1-12 (January...December)
0 = any month
t = all months

2) Day of the week

0 Sunday
1 Monday
2 Tuesday
3 Wednesday
4 Thursday
5 Friday
6 Saturday
7 Sunday

3) The 1st, 2nd, 3rd Monday, Tuesday, etc. of the month.

Examples:

*diary*

t all
0 every
& means the entry does not show up as marked in the calendar

%%(diary-float 2 1 4) Visit John
%%(diary-float 3 2 1) Visit John
%%(diary-float 3 3 2) Visit John
%%(diary-float 3 3 3) Visit John

%%(diary-float '(2 3 4 5 6 7 8 9 10 11) 2 3) 7pm Session Meeting
%%(diary-float t 3 0) 7pm Small Groups
%%(diary-float t 0 1) Holy Communion
%%(diary-float '(2 3 4 5 6 7 8 9 10 11) 2 1) 7pm Board Meeting
%%(diary-float '(2 4 6 8 10 12) 2 2) 7pm Presbytery Meeting

*ORG-EQUIVALENT*

* Holy Communion
%%(diary-float t 0 1) Holy Communion

* DIARY-BLOCK FOR DATE RANGES

Mark range i b

%%(and (diary-block 2 14 2019 2 21 2019)) Mondi works on window frames
%%(diary-block 2 22 2021 2 26 2021) Time off

*ORG-EQUIVALENT*

* Mondi works on window frames
<2021-02-22 Mon>-<2021-02-26 Fri>

* ANNIVERSARIES

Choose date in calendar

Choose date i a

Note date format month/day/year

%%(diary-anniversary 10 31 1988) Arthur's birthday
%%(diary-anniversary  7 22 1914) Bill Cook would be have been %d years old today
%%(diary-anniversary 1 21 1995) Raoul and Lucy have been married for %d years
%%(diary-anniversary  2 1 1998) Raoul Comninos has been in the Ministry for %d years
%%(diary-anniversary  2 25 2000) Jude Comninos is %d years old

*ORG-EQUIVALENT*

%%(org-anniversary 2005 4 1) Raoul has been at Tygerberg for %d years
%%(org-anniversary 1960 1 13) Tania Leonard is %d years old today (Birthday)
%%(org-anniversary 2021 2 26) Johanita and Jason Conradie have been married for %d year(s) (Wedding Anniversary)

Note that the date format is reversed: year/month/day

One can also use *org-date*:

%%(org-date t 12 16) Pierre and Sonja's wedding anniversary
%%(org-date t 2 24) Dad's birthday
%%(org-date t 2 23) Mom's birthday
%%(org-date t 3 21) Human Rights Day
%%(org-date t 4 27) Freedom Day

* CYCLIC

Cyclic diary entries repeat after a fixed interval of days. To create one, select the starting date and use the i c command.

%%(diary-cyclic 7 2 25 2021) Take my vitaim "D" tablet

*ORG-EQUIVALENT*

* <Any text>
%%(diary-cyclic 7 2 25 2021) Take my vitaim "D" tablet

[[file:older/recur_2.org][recur 2]]
