#+title: bookmark-plus
#+ROAM_TAGS: bookmark+ drew
#+created: [2021-03-03 Wed]
#+last_modified: [2021-03-03 Wed 17:22]

* Customize (ask Drew how to change)

That is, it describes each of the marked bookmarks. ‘C-down’ and ‘C-up’ move the cursor down and up a line, respectively, but they also show the description of the bookmark corresponding to the new cursor location. This is a quick way to cycle among bookmark descriptions, in the current sort order.

Don't get this:

There are several commands for jumping to a bookmark with tags. The completion candidates can be those bookmarks that have all tags in a given set, some tags in a given set, all tags matching a regexp, or some tags matching a regexp. You are prompted for the set of tags or the regexp to match.

C-x j t *
C-x j t +
icicle-bookmark-some-tags-regexp C-x j t % + 

---------------------------------------------------------------------

Bookmark+ ENHANCES VANILLA EMACS BOOKMARKS IN MANY WAYS
Program by Drew Adams, author of icicles, showkey, and dired+

* Bookmarks in Vanilla Emacs
=C-x-r-m=
=C-x-r-l=

* Installation
 - 8 libraries one must download + 4 optional libraries. I personally have downloaded them all.
 - Can be downloaded here: https://www.emacswiki.org/emacs/BookmarkPlus#h5o-51 from EmacsWiki
 - MELPA has decided to no longer accept Lisp libraries from EmacsWiki. Sadly, this includes Drew's libraries, even though they are read-only and therefore not insecure.
 - https://drive.google.com/drive/folders/1OMBPesRBH9Tb-idu9MtKM7nq2iBHTRtA?usp=sharing
 - Add this to =init.el=
   #+begin_example
   (add-to-list 'load-path "c:/red/.emacs.d/pack/bookmark+")
   (require 'bookmark+)
   #+end_example
   - The files must then be byte-compiled after loading the source files
   - Note: one must load =bookmark+-mac.el= before we byte-compile
   - =C-u M-x byte-recompile-directory=
 - One can check from time to time for any recent changes to the libraries by visiting this link:
https://www.emacswiki.org/emacs?action=rc;match=%5C.%28el%7Ctar%29%28%5C.gz%29%3F%24;from=1117497600;showedit=1
 - One must set a default bookmark file to store one's bookmarks
   The variable =bookmark-default-file= allows you to set that file. This must be done at the start before you use bookmark+

* Some key features
- Basically bookmark anything, not just files: directories, regions, URLs, snippets, Dired buffers, Functions, occur results, even Bookmark files
- Can access your bookmarks from anywhere =C-x j j=
- Different types of bookmarks coloured differently
  e.g. test.org
- Add tags to bookmarks and files, You can sort, show/hide, or mark bookmarks based on their tags.
- Add annotations to bookmarks
- Bookmarks can be arranged by frequency, tags, last use, etc.
- Bookmark a region of text
- Create snippets of text to be inserted later
- If you change the location to your bookmarks these are relocated better
- To bookmark a URL =bmkp-url-target-setd=

* Main commands

- Bookmark list =C-x x e=
- Create Bookmark =C-x x m=
  
* Basic Keys

*Some basic keys you can use anywhere:*
Bookmark the file you are editing: =C-x x m=
Jump to a bookmark: =C-x j j=
Tag a file (creates an autofile bookmark): C-x x t + a=
List/edit your bookmarks: =C-x x e= OR =C-x r l=

*Some keys you can use when in your bookmarks list:*
Add/remove some tags to/from a bookmark: =T += AND =T -=
Mark the bookmarks that have particular tags: =T m +=
Unmark all bookmarks: =M-DEL= OR =S-U=
Toggle marked/unmarked bookmarks: =t=
Dired the marked bookmarks: =M-d >=
Then you can,
Bookmark the Dired directory =C-x r m=

* Documentation

https://www.emacswiki.org/emacs/BookmarkPlus#h5o-51

Bookmark+ adds over 70 types of bookmark. (You can see what they all are by invoking function =bmkp-types-alist=.)

* Type-specific jump commands

bmkp-jump-to-type =C-x j :=

* Mark bookmark-list one's home page

(require 'bookmark+)
(bookmark-bmenu-list)
(switch-to-buffer "*Bookmark List*")

* Help

Get information on any bookmark =bmkp-describe-bookmark= (=C-h M=)

*In the bookmark list, =C-h RET= describes the bookmark under the cursor.*

=C-down= and =C-up= move the cursor down and up a line, respectively, but they also show the description of the bookmark corresponding to the new cursor location. This is a quick way to cycle among bookmark descriptions, in the current sort order.
=C-h-m= or =?= for detailed help (=bmkp-bmenu-mode-status-help=)

* Jump-destination highlighting

bmkp-crosshairs-flag

* Automatic Saving

set =bookmark-version-control= =t=

bookmark-save-flag

* Different Types of Jump Commands

bookmark-jump bookmark-jump-other-window C-x j j C-x 4 j j

bmkp-dired-jump C-x j d C-x j i
bmkp-file-jump C-x j f
bmkp-region-jump C-x j r
bmkp-jump-to-type C-x j : C-x 4 j :
bmkp-jump-to-url C-x j u

Jump to tags:

C-x j t *
C-x j t +
icicle-bookmark-some-tags-regexp C-x j t % + 

* Annotations

=bookmark-show-annotation= shows an annotation in read-only mode. You can use =C-x C-q= in the annotation buffer to switch to edit mode (and back again).
=bookmark-edit-annotation= edits an annotation
=bmkp-annotate= to create or edit an annotation
=C-c C-c= to save the result
=C-x C-k= if you do not want to save the changes.
=C-x C-q= and then y to confirm reverting the changes.
The variable =bookmark-automatically-show-annotations= means that a bookmark’s annotation is popped up whenever you jump to the bookmark
=a a= shows bookmark on the current line

One can also create *external annotations*.

You create an external annotation for a bookmark by using one of these forms as the annotation text.

     bmkp-annot-url: "FILE"
     bmkp-annot-url: "URL"
     bmkp-annot-url: "BOOKMARK"

In the *Bookmark List* display, =M-down= and =M-up= move the cursor down and up a line, respectively, but they also show the annotation, if any, of the bookmark at the new cursor location.

* Bookmark Tags

By default, you create bookmarks without tags and add tags later. If you prefer, you can customize option =bmkp-prompt-for-tags-flag= so you are prompted to add tags immediately whenever you set (create or update) a bookmark. (I have done this.)

To tag a file: =bmkp-tag-a-file=
To untag a file =bmkp-untag-a-file=
If you want to include a newline character in the tag use =C-q C-j=
To edit a tag =C-x x t e=
To edit a tag in the *bookmark list* =T e=
To list all tags =bmkp-tags-for-completion=

Most commands pertaining to tags are by default on prefix key =C-x x t=

*use =C-x x t C-h= to see all tag commands* (when not in *bookmakr list*)
*use =T C-h= when in *Bookmark List* (one can also use right mouse button)

* Last Place - Bookmark Tags Can Have Values

* Drew

In the ‘*Bookmark List*’ display, you can use ‘a’ [[in my system `a a']] to show or (with a prefix arg) [[do you mean C-u?]] 
